# Package Parameters
package_name: rec_sys_model

# Preprocessing Parameters
user_freq: 0.05
validation_freq: 0.25

# Model Parameters
data_version: 20m
data_dir_path: ./src/datasets
model_dir_path: ./db
results_dir_path: ./results
model_params:
  ret:
    epochs: 10
    scann_k: 15
    layer1: 16
    layer2: 8
  ran:
    epochs: 10

